version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: biblioteca_db
    environment:
      POSTGRES_USER: biblioteca
      POSTGRES_PASSWORD: biblioteca
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biblioteca -d biblioteca"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
